export { default as AngularOrbitIcon } from "./AngularIcon.astro";
export { default as AstroOrbitIcon } from "./AstroIcon.astro";
export { default as CopilotOrbitIcon } from "./CopilotIcon.astro";
export { default as CSharpOrbitIcon } from "./CSharpIcon.astro";
export { default as GithubOrbitIcon } from "./GithubIcon.astro";
export { default as ReactOrbitIcon } from "./ReactIcon.astro";
export { default as StarOrbitIcon } from "./StarIcon.astro";
export { default as TypescriptOrbitIcon } from "./TypescriptIcon.astro";
export { default as VSCodeOrbitIcon } from "./VSCodeIcon.astro";
